### ISSUE TITLE
ペア作成後の結果表示が読みにくい

### ISSUE THREAD

**Issue by miku0129** [Motoki-tech/PairMaker#15]
Pairsの結果に表示されるのが生徒人数分のペア＊20日分だと量が多く見にくい。
「作成完了です！」というメッセージを表示するだけにし、作成後はGoogle Spread Sheetを参照してもらうようにしてはどうか。
<img width="414" alt="スクリーンショット 2023-02-07 9 43 31" src="https://user-images.githubusercontent.com/58237700/217197450-ef2ac6fe-cab1-4a68-afe7-23175e11cedc.png">

**Comment by tamaroh** [comment]
いま表示させているのは「過去の名残」で反映させているだけです。整えてもないし、、
シートをみて確認すればいいのでここに表示させる必要はもうないですね。
