### ISSUE TITLE
出力先のSpreadSheetを指定できるようにする（ex. FND用とBTC用）

### ISSUE THREAD

**Issue by tamaroh** [Motoki-tech/PairMaker#17]
環境変数でSpreadSheetをしている
→現状DIG FNDが対象。BTCや別PJでも使用したいときは別途デプロイして環境変数を変えなければならない

・Gist CheckerみたいにシートIDを入力できるようにすれば対象を指定できる？
・シートの名称は固定、フォーマットは同一にする

**Comment by miku0129** [comment]
次期BTC4 開始に合わせて運用したいので、3月ごろまでに実装できれば良い。

**Comment by miku0129** [comment]
- [ ] Google splead sheet IDを現在の固定値から入力式にする
  
- BTC, FND ともシートの名称は固定、フォーマットも同一とする
- ペア作成の日数は、BTCでもペアを組む回数は大体20回程度なので20固定で可となった。（[議事録](https://www.notion.so/codechrysalis/Pair-Maker-4f5e004b9fe04c3aaaa1205c4046df53?pvs=4#d13670733c654c2fb62356385dc1eb0b)）
