### ISSUE TITLE
ペアを作る日数を指定できるようにしたい

### ISSUE THREAD

**Issue by tamaroh** [Motoki-tech/PairMaker#18]
related to #17 
別PJでペアを作りたい場合20日分とは限らないのでは？
何日分作るか設定できるようにしたい

**Comment by miku0129** [comment]
BTCであればペアワーク中心になるのは最初のスプリントの部分。スプリントのペアは毎日変わるわけではなく数日同じペアを組むこともある。また運用として20のペアを再利用することも可能。
実装そのものは比較的簡単に行える。
他の課題を優先とし本 issue は`not urgent`とする。

**Comment by miku0129** [comment]
BTC3では19回ペアを作成していた。BTCでペアを20回以上作成する機会は今のところなさそうなので、本issueは一旦クローズとする。
