### ISSUE TITLE
重複せずペアを組めるようにする

### ISSUE THREAD

**Issue by Motoki-tech** [Motoki-tech/PairMaker#2]
ペアが被らないように、全員が1度はペアを組めるように修正が必要

**Comment by tamaroh** [comment]
変数に履歴を格納する（最終的にはDB or SpreadSheet?)
2回目以降の作成時に履歴内にあるペアは除外する

**Comment by tamaroh** [comment]
ごく稀に同じペアが作られる
ロジックの見直しが必要？

**Comment by tamaroh** [comment]
リセットするとき両方ともリセットしなきゃいけない（いま片側しかリセットできていない）
1をリセットするならそれぞれの1もリセットする
