### ISSUE TITLE
Sheetにアカウント未設定でも「Done!」と表示される

### ISSUE THREAD

**Issue by tamaroh** [Motoki-tech/PairMaker#30]
アカウントの権限を設定していないSheetを指定するとDone!と表示されるがシートは変わっていない。
権限がなかったときのエラー処理追加が必要？

**Comment by miku0129** [comment]
サーバー側のエラーによりGoogle Spread sheetへの書き込みが失敗していてもアプリでは Doneと表示してしまっていた。
レスポンスのメッセージをアプリで表示できるよう仕様変更した。
![スクリーンショット 2023-04-06 182013](https://user-images.githubusercontent.com/58237700/230443193-14b01315-7a2e-4ddb-b7e1-7ee53eec51a6.jpg)
